### ISSUE TITLE
Support for missing `Task` state fields

### ISSUE THREAD

**Issue by nibble-4bits** [nibble-4bits/aws-local-stepfunctions#5]
Add support for missing `Task` state fields: 
* [x] `Retry` (added in #40)
* [x] `Catch` (added in #40)
* [x] `TimeoutSeconds` (added in #73)
* [x] `TimeoutSecondsPath` (added in #73)
* [ ] `HeartbeatSeconds`
* [ ] `HeartbeatSecondsPath`
