### ISSUE TITLE
Support for new fields added to the spec on 2023-09-07

### ISSUE THREAD

**Issue by nibble-4bits** [nibble-4bits/aws-local-stepfunctions#67]
A couple of new fields have been added to the `Fail` state and the `Retrier` objects:

- `Fail` state
   - [x] `ErrorPath` (added in #76)
   - [x] `CausePath` (added in #76)
- `Retrier` object
   - [x]  `MaxDelaySeconds` (added in #75)
   - [x] `JitterStrategy` (added in #75)
